### PR TITLE
server side code

### PR DESCRIPTION
**Pull request by lucasgonze**
Hi Jamie,

Your library is ultra useful.

One problem - inserting the HTML into your document. I could copy and paste your example HTML, but then I would have two problems.

Problem one - if you do any maintenance on your list, such as when a country renames itself, my version gets out of sync. Better to have the country list be in a shared public repo.

Problem two - setting the default selection in the list requires some new code by people using the country list. Better to have that code to create the selection come with the library.

I created a Node.js package to do both of those and added it to a clone of your repo so that this code can be updated and maintained in a single bundle. That's what this pull request is.

### CODE REVIEW

**Comment by patrickt010** [comment]
@lucasgonze This is awesome good work do you think you can create an NPM version?

**Comment by lucasgonze** [comment]
That's a good idea. I'll look into it. 

I didn't do it before because there's a bit of complexity to expose your client side stuff, because NPM packages go into a directory that isn't visible via the web server.

**Comment by patrickt010** [comment]
Ya not sure about the complexities but it would potentially make it a lot easier for node.js adoption.

**Comment by lucasgonze** [comment]
Agreed.

**Comment by lucasgonze** [comment]
Done:

https://npmjs.org/package/country-selector

**Comment by patrickt010** [comment]
This is awesome thanks can not wait to give it a go.

**Comment by lucasgonze** [comment]
https://npmjs.org/package/country-selector

**Comment by lucasgonze** [comment]
Looks like this has never been pulled back into the master. Is there anything I can do to help that along?

**Comment by jamieholst** [comment]
Hi there,

First of all, thanks a bunch for your interest and work. Sorry for being MIA, we're currently busy writing a book and the new Github notifications system also threw me for a loop there :)

There are two reasons I'm hesitant to merge this pull request. 

1) It aims to solve a problem that I would rather not be responsible for solving: country lists. Country lists are hugely political and I therefore just opt for using an ISO standard in the example so people can try out the plugin's functionality but then generally encourage people to create their own list.

2) While Node.js seems awesome I have next to zero experience with it (we're talking the "Hello world" example stage), and I reckon I'm not alone in this. Therefore I'm not a huge fan of adding Node as a dependency for the sake of convenience.

**Comment by jamieholst** [comment]
If you want to keep the Node setup as a fork I can link to that from the readme as a service to all the people who are using Node..?

**Comment by lucasgonze** [comment]
Let's do that.

I agree that the country lists are the tip of the iceberg. That's why I
refactored that code in the most recent push.

Ideally the country name lists would be a dedicated repo with many projects
pulling it dynamically, like a Wikipedia article. selectToAutocomplete
would be just one user. However I can't see a way to do the
data-relevancy-booster
then. Maybe the solution is to not bother with it.

-L

**Comment by jamieholst** [comment]
The relevancy booster can of course be added and used any way you want, but my intention was that people would query their customer / user database from time to time and assign relevancy values according to frequency. That is, you would extend the list with relevancy boosters depending on country usage. Therefore I always imagined the country list to be extended with relevancy boosters programatically (which makes it very easy to add but also completely implementation-specific), but you could of course do it manually too.

So in the scenario you present with a country list in a dedicated repo, then I'd have a script that automatically pulled the latest version of that list and then queried the orders in my database and assigned each an appropriate data-relevancy-booster value, and then saved all this to my desired format (JSON, JS partial, whatever you prefer).

**Pull request closed without merging**
