### PR TITLE
Change event on select is now fired.

### PR DESCRIPTION
**Pull request by ilivewithian**
The change event was not being fired when an item was selected.

### CODE REVIEW

**Comment by kyeotic** [comment]
This code causes the change event to fire on change, and then again on blur.

**Comment by jamieholst** [comment]
Thanks for the request, but I guess it should only fire on actual change (as pointed out by tyrsius) – so only when a new value is selected (we'd want to simulate standard 'select' tag change-behavior, so if the same value was selected it shouldn't be triggered). 

I'm thinking this could be achieved by tracking the old value and then comparing against the new value on any call to 'update_select_value'.

Would this fit the intended use case?

**Comment by kyeotic** [comment]
I would think so

**Comment by ilivewithian** [comment]
That would be fine for my needs, this pull should be closed.

**Comment by jamieholst** [comment]
Fixed in this pull request: https://github.com/JamieAppleseed/selectToAutocomplete/pull/14

**Pull request closed without merging**
